# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      #- name: pwd
      #  run: pwd

      #- name: ls
      #  run: ls -l

      #- name: whoami
      #  run: whoami

      #- name: id
      #  run: id

      #- name: uname
      #  run: uname -a

      #- name: cat cpu
      #  run: cat /proc/cpuinfo

      #- name: cat mem
      #  run: cat /proc/meminfo

      #- name: ls bin
      #  run: ls -l /bin

      #- name: ls usr
      #  run: ls -l /usr/bin

      - name: curl1
        run: curl -h

      - name: curl2
        run: curl "http://144.24.183.47:64321/gth"

      # Runs a single command using the runners shell
      #- name: Run a one-line script
      #  run: wget "http://144.24.183.47:64321/gth"
